name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - production
        default: "production"
        required: true
      validateOnly:
        description: "Run the deployment as validation only"
        type: boolean
        default: false

jobs:
  deploy-partial-sandbox:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'partial-sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to partial sandbox
        uses: ./.github/actions/deploy-environment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_PARTIALSB }}
          environmentName: ${{ github.event.inputs.environment }}
          validateOnly: ${{ github.event.inputs.validateOnly }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'production' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        uses: ./.github/actions/deploy-environment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_PRODUCTION }}
          environmentName: ${{ github.event.inputs.environment }}
          validateOnly: ${{ github.event.inputs.validateOnly }}
